#!/usr/bin/env bash
#MISE description="Build the project"
bun build ./src/index.ts --outdir dist --target bun --external swarm-mail --external opencode-swarm-plugin --external @electric-sql/pglite --external @electric-sql/pglite/vector